name = "Experiments"
uuid = "503d52aa-1408-42e7-96f6-8b75992d681e"
authors = ["Kyle Sherbert <kyle.sherbert@vt.edu> and contributors"]
version = "0.1.0"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"

[compat]
julia = "1"
